### ISSUE TITLE
Artifacts in source

### ISSUE THREAD

**Issue by wallstop** [Valkryst/VRoguelike#1]
It'd be cool to leverage a tool like maven to pull artifacts from the relevant github repos (VTerminal, VRadio) instead of checking them into source.

Something like [this](https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github).

**Comment by Valkryst** [comment]
Thanks for bringing that up, it gave me something to do at work for a little while

The project should work properly using the new JitPack Maven dependencies now.
