### ISSUE TITLE
 Using Project Lombok

### ISSUE THREAD

**Issue by Andres6936** [Valkryst/VRoguelike#8]
Good morning....

I have reviewed the code of the project and have noticed that you use Project Lombok to save time in the development of the project, however Project Lombok is not part of Java by default, I have not worked with Project Lombok and it is difficult to read the code, this is a problem for all those people who want to modify the code or learn from it, you can make the code more readable leaving Project Lombok apart in order to reduce the time it takes.

**Comment by Valkryst** [comment]
Morning,

Thanks for taking a look through the code. I do use Lombok to write the code a little bit faster, to auto-generate (and keep updated) a few functions (toString, equals, hashCode), and to make the code easier to read (if you learn just a little bit of Lombok).

I'll definitely consider rewriting the code without Lombok, when VRoguelike is finished and I write a tutorial on how to use VTerminal to write a roguelike (using my experience with VRoguelike), but I'll be using Lombok in the project until then.

Just so you can read the code a bit more easily, here's a crash-course on the annotations that I usually use. If you ever want to learn more about Lombok in the future, you can read-up on the other annotations [here](https://projectlombok.org/features/all).

* `@Getter` - Generates a getter (accessor) function for a variable.
* `@Setter` - Generates a settet (mutator) function for a variable.
* `@NonNull` - Throws a NullPointerException if a variable is null.
* `@Data` - When you use this on a class, it adds @Getter and @Setter to all class (instance) variables and generates a toString, equals, and hashCode function for the class.

---

## Example for `@Getter`:

```java
public class TestClass {
    @Getter private int number;

    public TestClass(int number) {
        this.number = number;
    }
}
```

The code above is the same as typing...

```java
public class TestClass {
    private int number;

    public TestClass(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }
}
```

## Example for `@Setter`:

```java
public class TestClass {
    @Setter private int number;

    public TestClass(int number) {
        this.number = number;
    }
}
```

The code above is the same as typing...

```java
public class TestClass {
    private int number;

    public TestClass(int number) {
        this.number = number;
    }

    public int setNumber(int number) {
        this.number = number;
    }
}
```

## Example for `@NonNull`:

```java
public class TestClass {
    private String sentence;

    public TestClass(@NonNull String sentence) {
        this.sentence = sentence;
    }
}
```

The code above is the same as typing...

```java
public class TestClass {
    private String sentence;

    public TestClass(String sentence) {
        if (sentence == null) {
            throw new NullPointerException("The variable 'sentence' cannot be null.");
        }
   
        this.sentence = sentence;
    }
}
```
